name: Buildozer APK Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with official Kivy Action
        uses: kivy/buildozer-action@master
        id: buildozer
        with:
          command: buildozer -v android debug apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.apk-path }}
